In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [33]:
df = pd.read_csv('FourExampleDataSets.csv')
datasets = np.array(df)
datasets

array([[10.  ,  8.04, 10.  ,  9.14, 10.  ,  7.46,  8.  ,  6.58],
       [ 8.  ,  6.95,  8.  ,  8.14,  8.  ,  6.77,  8.  ,  5.76],
       [13.  ,  7.58, 13.  ,  8.74, 13.  , 12.74,  8.  ,  7.71],
       [ 9.  ,  8.81,  9.  ,  8.77,  9.  ,  7.11,  8.  ,  8.84],
       [11.  ,  8.33, 11.  ,  9.26, 11.  ,  7.81,  8.  ,  8.47],
       [14.  ,  9.96, 14.  ,  8.1 , 14.  ,  8.84,  8.  ,  7.04],
       [ 6.  ,  7.24,  6.  ,  6.13,  6.  ,  6.08,  8.  ,  5.25],
       [ 4.  ,  4.26,  4.  ,  3.1 ,  4.  ,  5.39, 19.  , 12.5 ],
       [12.  , 10.84, 12.  ,  9.13, 12.  ,  8.15,  8.  ,  5.56],
       [ 7.  ,  4.82,  7.  ,  7.26,  7.  ,  6.42,  8.  ,  7.91],
       [ 5.  ,  5.68,  5.  ,  4.74,  5.  ,  5.73,  8.  ,  6.89]])

In [34]:
x1 = datasets[:,0]
y1 = datasets[:,1]
x2 = datasets[:,2]
y2 = datasets[:,3]
x3 = datasets[:,4]
y3 = datasets[:,5]
x4 = datasets[:,6]
y4 = datasets[:,7]

In [35]:
x1_y1 = np.cov(x1,y1)
x1_y1

array([[11.        ,  5.501     ],
       [ 5.501     ,  4.12726909]])

In [36]:
x2_y2 = np.cov(x2,y2)
x3_y3 = np.cov(x3,y3)
x4_y4 = np.cov(x4,y4)

In [38]:
lala = np.diag(x1_y1)
lala

array([11.        ,  4.12726909])

LinAlgError: Singular matrix