In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
def LS(G,d):
    return np.linalg.inv(G.T@G)@G.T@d

In [4]:
G = (([0.2,0.4]))
def linear_G(blah):
    intercept = np.repeat(1,len(blah))
    return np.vstack((intercept, blah)).T
def alt_linear(blah):
    G = np.ones((blah.shape[0],2))
    G [:,1] = blah
    return G

In [5]:
G_matrix = linear_G(G)
G_matrix

array([[1. , 0.2],
       [1. , 0.4]])

In [6]:
d_vector = (([3.8/10,6.8/10]))
d_vector

[0.38, 0.6799999999999999]

In [7]:
LS = LS(G_matrix,d_vector)
LS

array([0.08, 1.5 ])

In [8]:
dCO2_NA = 0.38/0.2
dCO2_EA = 0.68/0.4
list_dCO2 = ([dCO2_NA,dCO2_EA])
weight_matrix = ([0.2**2,0.4**2])

weighted_avg_dCO2 = np.average(list_dCO2,weights=weight_matrix)

weighted_avg_dCO2

1.7399999999999998

In [12]:
residuals = G*LS-d_vector
residuals

array([-0.364, -0.08 ])

In [15]:
dprediction=G@LS

In [17]:
residualss = dprediction-d_vector

In [18]:
from numpy import array
from numpy.linalg import norm

In [21]:
np.sqrt(residualss[0]**2+residualss[1]**2)
np.linalg.norm(residualss)

0.24452402744924684